### ISSUE TITLE
Payload is null in scheduled events

### ISSUE THREAD

**Issue by ShaunEgan** [walmartlabs/bigben#2]
## Problem
When scheduling an event that will result in a event being fired at some point in the future, the payload received by the tenant is `null`, regardless of what was set during the schedule.

When executing the event to be fired using `dryrun`, the payload is delivered as expected.

When scheduling an event in the past, which results in an instant firing of the event, the payload is delivered as expected.

When delivering an event in the `ERROR` state when the target tenant is available, the payload is delivered as expected.

## Example request
`POST {{host}}/events/schedule`
```json
[
  {
    "id": "my-event-id",
    "eventTime": "some time in the future",
    "tenant": "my-tenant",
    "payload": "my-payload",
    "mode": "UPSERT"
  }
]
```

Results in the following body being delivered
```
{
  "id": "my-event-id",
  "eventTime": "some time",
  "tenant": "my-tenant",
  "mode": "UPSERT",
  "payload": null,
  "eventId": "some uuid",
  "triggeredAt": "some time",
  "eventStatus": "triggered",
  "error": null
}
```

All other scenarios the payload is delivered.

**Comment by sandeepmalik** [comment]
This is fixed in commit be4dfdcac4115b03961f31bf8d16e1c3a8eaf88d
