### ISSUE TITLE
How to setup bigben multinode cluster on different machines

### ISSUE THREAD

**Issue by abhisheksahani** [walmartlabs/bigben#24]

**Comment by anonymus309** [comment]
Hi Abhishek
For non docker environment.
make use of overrides.yaml file or alternatively You can modify bigben.yaml
for ex:
hz:
  network.members: 172.17.12.132:5701,172.17.12.131:5701,172.17.13.176:5701

modify app_run.sh as per your requirement as it contain the startup command.
