### ISSUE TITLE
Remove schedules event?

### ISSUE THREAD

**Issue by p-bakker** [walmartlabs/bigben#29]
Hi,

Is it possible to remove schedules events? 

Background of this question: am looking to use BigBen for scheduling notifications based on (editable) events on Calendars that use support recurrence.

My idea is schedule the next occurrence of the calendar event as a scheduled event in BigBen, but I need to take into account the user changing or deleting the calendar event, which means removing the scheduled event in BigBen if the next occurrence has changed.

**Comment by sandeepmalik** [comment]
Hi, 
yes, you need to update the same event (same tenant and id, with mode as REMOVE). It will remove the event.

e.g. 
{
"tenant": "x",
"id": "y",
"mode": "REMOVE"
}

(from event's schema in READ.me):

"mode": { 
      "type": "string",
      "enum": ["UPSERT", "REMOVE"],
      "default": "UPSERT",
      "description": "Use REMOVE to delete an event, UPSERT to add/update an event"
    }

**Comment by p-bakker** [comment]
Thank you for the quick response and sorry I missed it in the readme
