### ISSUE TITLE
Docker images for BigBen

### ISSUE THREAD

**Issue by aaabramov** [walmartlabs/bigben#7]
It would be awesome to provide docker images or at least instructions how to create proper BigBen docker deployments.

Ideally, include `docker-compose.yml` example in readme.

I'm gonna try that and in case of success I will create proper PR for that.

**Comment by sandeepmalik** [comment]
That would be great. Thanks Andrii for the help. Let me know if you need something.

Thanks,
Sandeep

**Comment by aaabramov** [comment]
@sandeepmalik regarding `lib/src/main/resources/hz.template.xml`.
It should be somehow mounted into hazelcast image?

**Comment by sandeepmalik** [comment]
Hi Andrii,

We are running hz in embedded mode so no separate mounting is required.
This error usually indicates that real cause is elsewhere. Most likely
server didn't start properly which caused hazelcast to shutdown as well and
when scheduler tried to access hz in a separate thread it threw 'not
active' error.

If you can send me the complete logs then I'll be able to help more.

Thanks
Sandeep

**Comment by aaabramov** [comment]
Hi,  
I collected all logs. Maybe it is somehow related to docker networks.. but still strange.
Because BigBen sees Cassandra with no issues.

[hz-issue.zip](https://github.com/walmartlabs/bigben/files/2641267/hz-issue.zip)

I can create patch / WIP PR if needed.

**Comment by aaabramov** [comment]
My main goal is to prepare docker-compose at least for development / trying purposes

**Comment by sandeepmalik** [comment]
Ahh I see now, in your yaml file, you have removed the modules but left the key "modules" there (which yaml parser interprets as having null value). The code throws a null pointer on server start up and shuts down hazelcast. I'll fix and push the fix. For the time being, just remove the "modules" key as well from the yaml file and it should be fine.

**Comment by sandeepmalik** [comment]
As a matter of fact, I fixed this issue some time back in dev but haven't merged the changes back to master. 
https://github.com/walmartlabs/bigben/commit/9a4f776c79cc9d24d225970d9dd7a8a5cae0d48b#diff-24b3a0cc809cf5576c60c4377309fc63R119

I'll do that soon, for the time being just remove the "modules" key and redeploy. Let me know if any issues.

**Comment by aaabramov** [comment]
Awesome, it fixed the issue.
`04-Dec-2018 07:30:58.430 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 24124 ms`

**Comment by sandeepmalik** [comment]
Glad, it worked!

**Comment by zhandosso** [comment]
Hi @aaabramov, can't find docker-compose file. 
Could you pls share, if you have implemented already?

**Comment by sandeepmalik** [comment]
Docker image is available now. There's a docker-compose file as well for dev/testing purposes. I am closing this ticket.
