### ISSUE TITLE
Bigben Kafka consumer dies whenever topic has >1 partition

### ISSUE THREAD

**Issue by ajzwu8** [walmartlabs/bigben#8]
Setting the topics under kafka.topics bigben listens on to 1 for both replication factor and 1 partition works, but anytime we try and go beyond that, bigben consumers error out with the following message:

`2019-01-10 01:21:19.931 ERROR [messageProcessor#0] KafkaMessageProcessor:172 - unknown exception, closing the consumer
java.lang.IllegalStateException: No current assignment for partition bigben-1
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.assignedState(SubscriptionState.java:269)
	at org.apache.kafka.clients.consumer.internals.SubscriptionState.pause(SubscriptionState.java:404)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pause(KafkaConsumer.java:1526)
	at com.walmartlabs.bigben.kafka.KafkaMessageProcessor.init(kafka.kt:140)
	at com.walmartlabs.bigben.BigBen$3$1$1.run(BigBen.kt:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

We are using the `master` branch.

**Comment by sandeepmalik** [comment]
Looks like the consumer is trying to pause reading from partitions at a time when no partitions are assigned (or are being rebalanced). Could you specify the sequence of steps and app/topic profile (how many nodes, total partitions, etc) that lead to this error and I'll try to replicate it at my end.

**Comment by ajzwu8** [comment]
@sandeepmalik In terms of bigben setup, we didn't edit the bigben.yaml file too much beyond what the original defaults were and connecting it to our own cassandra/kafka clusters and setting enable.auto.commit to true. So bigben would have been initiated with the default 8 kafka consumers listening on the 'bigben' topic.

Topics were created using the kafka bin utils as such:
`JMX_PORT=53000 ./kafka-topics.sh --zookeeper "<our zookeeper>" --create --topic bigben --replication-factor 3 --partitions 16`

We have a simple node script that creates a producer for topic 'bigben', then registers a tenant creates a consumer for the output topic of the tenant. That's enough to reproduce the error message shown above if the partitions are greater than 1.

The kafka cluster is using kafka v2.0.0.

Please let me know if any additional details/code is needed.

**Comment by sandeepmalik** [comment]
Ahh I see the issue, thanks for pointing it out. Working on the fix.

**Comment by ajzwu8** [comment]
Thanks @sandeepmalik! Do you have an ETA for merging this into master?

**Comment by sandeepmalik** [comment]
Most likely by EoD Monday of coming week.

**Comment by sandeepmalik** [comment]
I merged the dev branch. Please test and let me know if the issue is still there.

**Comment by ajzwu8** [comment]
@sandeepmalik Looks good, ran the same test with more partitions. Thanks a lot.
